spring:
  activiti:
    database-schema-update: true
    history-level: full
    db-history-used: true
    check-process-definitions: false # 自动部署验证设置:true-开启（默认）、false-关闭
  datasource:
    url: jdbc:mysql://192.168.200.128:33060/mos?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialization-mode: always
  security:
    user:
      name: admin
      password: admin

swagger:
  enabled: true

